apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: knph9quu2-go
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-8820061365.ltwz.p3.openshiftapps.com/rhtap/rhtap-qe:b52e68bc67ed383b355686ef350f7654b314c239@sha256:8d6b199ffbe549b02c9a859d4dca4cda9c9293d0d7f31007b367c5294ea0f689
          name: container-image
